repos:
  - repo: local
    hooks:
      - id: sort_makefile
        name: sort_makefile
        entry: python sort_makefile.py
        language: python
        pass_filenames: false
        args: ['Makefile']